name: Create Test Issue
on:
  issues:
    types: [opened]
jobs:
    create-test-issue:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Create Test Issue
          run: |
            token=${{ secrets.GITHUB_TOKEN }}
            title=$(jq -r '.issue.title' $GITHUB_EVENT_PATH)
            body="This is a test issue created for $title."
            url="https://api.github.com/repos/${{ github.repository }}/issues"
                    
            curl -X POST \
              -H "Authorization: Bearer $token" \
              -H "Accept: application/vnd.github.v3+json" \
              "$url" \
              -d "{\"title\":\"Test $title\",\"body\":\"$body\"}"